name: ynab_copilot
description: "An app to better visualize and analyze your YNAB data."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_web_auth: ^0.5.0
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  swipeable_page_route: ^0.4.2
  syncfusion_flutter_charts: ^25.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/demo_data/
